language: node_js
node_js:
  - '0.10'
before_install:
  - currentfolder=${PWD##*/}
  - if [ "$currentfolder" != 'generator-vs-angular' ]; then cd .. && eval "mv $currentfolder generator-vs-angular" && cd generator-vs-angular; fi

